# Build and publish a tagged version.
name: Release Tag 

on: 
  push:
    tags:
      - "**" 

jobs:
  ci:
    uses: ./.github/workflows/ci.yml

  publish:
    uses: ./.github/workflows/publish.yml
    needs: ci
  